"""Teacher-prepared question bank: 15 MCQs per subject.
Each item: q, options (4), correct (A-D letter), explanation, concept.
Concepts map to illustrations.py for the learn-from-mistake moment.
"""

QUESTIONS = {
"Science": [
{"q": "Which gas do plants take in during photosynthesis?", "options": ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], "correct": "C", "explanation": "Plants take in carbon dioxide and release oxygen during photosynthesis.", "concept": "photosynthesis"},
{"q": "What happens when water reaches its boiling point?", "options": ["It becomes ice", "It becomes water vapor", "It disappears", "It becomes soil"], "correct": "B", "explanation": "Liquid water heated to boiling point changes into a gas called water vapor.", "concept": "states of matter"},
{"q": "Which planet is known as the Red Planet?", "options": ["Venus", "Mars", "Jupiter", "Mercury"], "correct": "B", "explanation": "Mars looks red because of iron oxide (rust) on its surface.", "concept": "solar system"},
{"q": "What force pulls objects toward the Earth?", "options": ["Magnetism", "Friction", "Gravity", "Push"], "correct": "C", "explanation": "Gravity pulls everything toward the centre of the Earth.", "concept": "gravity"},
{"q": "Which part of the plant makes food?", "options": ["Root", "Stem", "Leaf", "Flower"], "correct": "C", "explanation": "Leaves contain chlorophyll and make food by photosynthesis.", "concept": "plant structure"},
{"q": "How many states of matter are commonly taught (solid, liquid, gas)?", "options": ["2", "3", "4", "5"], "correct": "B", "explanation": "The three common states are solid, liquid and gas.", "concept": "states of matter"},
{"q": "What does a food chain always start with?", "options": ["A carnivore", "A producer", "A decomposer", "A consumer"], "correct": "B", "explanation": "Every food chain starts with a producer, usually a green plant.", "concept": "food chain"},
{"q": "Which material lets electricity pass easily?", "options": ["Rubber", "Wood", "Copper", "Plastic"], "correct": "C", "explanation": "Copper is a conductor; rubber, wood and plastic are insulators.", "concept": "electricity"},
{"q": "Where does the water cycle start when water rises into the air?", "options": ["Precipitation", "Collection", "Evaporation", "Condensation"], "correct": "C", "explanation": "Evaporation is when liquid water becomes vapor and rises.", "concept": "water cycle"},
{"q": "Which simple machine uses a fulcrum?", "options": ["Lever", "Rope", "Wheel", "Screw"], "correct": "A", "explanation": "A lever turns around a fixed point called the fulcrum.", "concept": "forces and motion"},
{"q": "What do we call animals that eat only plants?", "options": ["Carnivores", "Herbivores", "Omnivores", "Predators"], "correct": "B", "explanation": "Herbivores eat only plants.", "concept": "food chain"},
{"q": "Which planet is closest to the Sun?", "options": ["Earth", "Venus", "Mercury", "Mars"], "correct": "C", "explanation": "Mercury is the closest planet to the Sun.", "concept": "solar system"},
{"q": "What is ice an example of?", "options": ["Gas", "Liquid", "Solid", "Vapor"], "correct": "C", "explanation": "Ice is water in its solid state.", "concept": "states of matter"},
{"q": "Which part of the plant absorbs water?", "options": ["Leaf", "Flower", "Stem", "Root"], "correct": "D", "explanation": "Roots absorb water from the soil.", "concept": "plant structure"},
{"q": "What pushes a falling parachute upward?", "options": ["Gravity", "Air resistance", "Magnetism", "Light"], "correct": "B", "explanation": "Air resistance pushes up while gravity pulls down.", "concept": "forces and motion"},
],
"Geography": [
{"q": "Which is the largest ocean?", "options": ["Atlantic", "Indian", "Arctic", "Pacific"], "correct": "D", "explanation": "The Pacific is the largest ocean.", "concept": "oceans"},
{"q": "Which continent is Egypt in?", "options": ["Asia", "Africa", "Europe", "South America"], "correct": "B", "explanation": "Egypt is in Africa.", "concept": "continents"},
{"q": "What is the capital of France?", "options": ["London", "Paris", "Rome", "Madrid"], "correct": "B", "explanation": "Paris is the capital of France.", "concept": "capitals"},
{"q": "Which river flows through Egypt?", "options": ["Amazon", "Nile", "Mississippi", "Danube"], "correct": "B", "explanation": "The Nile flows through Egypt.", "concept": "rivers"},
{"q": "What is a mountain with an opening that erupts?", "options": ["Hill", "Valley", "Volcano", "Plateau"], "correct": "C", "explanation": "A volcano erupts lava and ash.", "concept": "volcano"},
{"q": "Which desert is the largest hot desert?", "options": ["Gobi", "Sahara", "Kalahari", "Atacama"], "correct": "B", "explanation": "The Sahara is the largest hot desert.", "concept": "deserts"},
{"q": "How many continents are there?", "options": ["5", "6", "7", "8"], "correct": "C", "explanation": "There are 7 continents.", "concept": "continents"},
{"q": "What do we call land completely surrounded by water?", "options": ["Peninsula", "Island", "Isthmus", "Delta"], "correct": "B", "explanation": "An island is land surrounded by water.", "concept": "landforms"},
{"q": "Which direction does the sun rise from?", "options": ["North", "South", "East", "West"], "correct": "C", "explanation": "The sun rises in the east.", "concept": "compass"},
{"q": "What is the imaginary line around the middle of Earth?", "options": ["Prime Meridian", "Equator", "Tropic", "Axis"], "correct": "B", "explanation": "The Equator circles the middle of Earth.", "concept": "globe"},
{"q": "Which is the longest river in the world (often listed)?", "options": ["Nile", "Amazon", "Yangtze", "Congo"], "correct": "A", "explanation": "The Nile is usually listed as the longest river.", "concept": "rivers"},
{"q": "What map symbol shows height above sea level?", "options": ["Compass", "Scale", "Contour line", "Legend"], "correct": "C", "explanation": "Contour lines join places of equal height.", "concept": "maps"},
{"q": "Which climate has rain all year and dense trees?", "options": ["Desert", "Polar", "Rainforest", "Mediterranean"], "correct": "C", "explanation": "Rainforests are wet all year.", "concept": "climate"},
{"q": "What is the capital of Egypt?", "options": ["Giza", "Alexandria", "Cairo", "Luxor"], "correct": "C", "explanation": "Cairo is the capital of Egypt.", "concept": "capitals"},
{"q": "Which ocean is west of Africa?", "options": ["Pacific", "Atlantic", "Indian", "Arctic"], "correct": "B", "explanation": "The Atlantic Ocean is west of Africa.", "concept": "oceans"},
],
"Mathematics": [
{"q": "What is 7 x 8?", "options": ["54", "56", "63", "48"], "correct": "B", "explanation": "7 times 8 equals 56.", "concept": "multiplication"},
{"q": "What is 1/2 + 1/4?", "options": ["1/6", "2/4", "3/4", "1/4"], "correct": "C", "explanation": "1/2 = 2/4, so 2/4 + 1/4 = 3/4.", "concept": "fractions"},
{"q": "Which number is prime?", "options": ["4", "6", "9", "7"], "correct": "D", "explanation": "7 has only factors 1 and 7.", "concept": "primes"},
{"q": "What is 100 - 37?", "options": ["63", "73", "53", "67"], "correct": "A", "explanation": "100 minus 37 is 63.", "concept": "subtraction"},
{"q": "How many degrees in a right angle?", "options": ["45", "90", "180", "360"], "correct": "B", "explanation": "A right angle is 90 degrees.", "concept": "angles"},
{"q": "What is the next number: 2, 4, 8, 16, ...?", "options": ["20", "24", "32", "18"], "correct": "C", "explanation": "Each number doubles, so next is 32.", "concept": "patterns"},
{"q": "What is 3/4 as a decimal?", "options": ["0.34", "0.75", "0.43", "0.5"], "correct": "B", "explanation": "3 divided by 4 is 0.75.", "concept": "fractions"},
{"q": "How many sides does a hexagon have?", "options": ["5", "6", "7", "8"], "correct": "B", "explanation": "A hexagon has 6 sides.", "concept": "shapes"},
{"q": "What is 12 x 12?", "options": ["124", "132", "144", "142"], "correct": "C", "explanation": "12 squared is 144.", "concept": "multiplication"},
{"q": "Which fraction is biggest?", "options": ["1/4", "1/3", "1/5", "1/8"], "correct": "B", "explanation": "1/3 is the largest piece.", "concept": "fractions"},
{"q": "What is the area of a 5cm by 4cm rectangle?", "options": ["9 sq cm", "20 sq cm", "18 sq cm", "10 sq cm"], "correct": "B", "explanation": "Area = 5 x 4 = 20 square cm.", "concept": "area"},
{"q": "What is 15% of 200?", "options": ["15", "20", "30", "25"], "correct": "C", "explanation": "10% is 20 and 5% is 10, so 30.", "concept": "percentages"},
{"q": "Which is an even number?", "options": ["13", "17", "22", "31"], "correct": "C", "explanation": "22 divides by 2 exactly.", "concept": "numbers"},
{"q": "What is 9 + 9 + 9?", "options": ["18", "27", "29", "36"], "correct": "B", "explanation": "9 three times is 27.", "concept": "addition"},
{"q": "How many minutes in 2 hours?", "options": ["60", "100", "120", "180"], "correct": "C", "explanation": "2 x 60 = 120 minutes.", "concept": "time"},
],
"History": [
{"q": "Who recorded one of the oldest algorithms around 300 BC?", "options": ["Pythagoras", "Euclid", "Aristotle", "Archimedes"], "correct": "B", "explanation": "Euclid recorded a famous algorithm around 300 BC.", "concept": "ancient greece"},
{"q": "The pyramids of Giza were built as...?", "options": ["Palaces", "Tombs", "Schools", "Markets"], "correct": "B", "explanation": "Pyramids were tombs for pharaohs.", "concept": "ancient egypt"},
{"q": "Which civilization used hieroglyphs?", "options": ["Roman", "Greek", "Egyptian", "Viking"], "correct": "C", "explanation": "Ancient Egyptians wrote with hieroglyphs.", "concept": "ancient egypt"},
{"q": "The Romans spoke which language?", "options": ["Greek", "Latin", "Arabic", "French"], "correct": "B", "explanation": "Romans spoke Latin.", "concept": "rome"},
{"q": "Which invention helped ships navigate with direction?", "options": ["Compass", "Engine", "Telescope", "Anchor"], "correct": "A", "explanation": "The compass shows direction.", "concept": "exploration"},
{"q": "Who was the first man on the moon (1969)?", "options": ["Yuri Gagarin", "Buzz Aldrin", "Neil Armstrong", "Michael Collins"], "correct": "C", "explanation": "Neil Armstrong stepped first in 1969.", "concept": "modern history"},
{"q": "The Great Wall is in which country?", "options": ["India", "China", "Egypt", "Mexico"], "correct": "B", "explanation": "The Great Wall is in China.", "concept": "china"},
{"q": "Vikings came from which region?", "options": ["South America", "Scandinavia", "Africa", "Australia"], "correct": "B", "explanation": "Vikings came from Scandinavia.", "concept": "vikings"},
{"q": "What do we call objects from the past in museums?", "options": ["Artefacts", "Souvenirs", "Toys", "Copies"], "correct": "A", "explanation": "Artefacts are historical objects.", "concept": "history skills"},
{"q": "Which scholar is linked to algebra (Al-Khwarizmi)?", "options": ["Ibn Battuta", "Al-Khwarizmi", "Ibn Khaldun", "Averroes"], "correct": "B", "explanation": "Al-Khwarizmi's work gave us the word algorithm and algebra.", "concept": "islamic golden age"},
{"q": "Ancient Olympic games began in which country?", "options": ["Egypt", "Greece", "Rome", "Persia"], "correct": "B", "explanation": "Olympics began in ancient Greece.", "concept": "ancient greece"},
{"q": "What material did ancient Egyptians write on?", "options": ["Paper", "Papyrus", "Silk", "Clay tablets"], "correct": "B", "explanation": "Egyptians made papyrus from reeds.", "concept": "ancient egypt"},
{"q": "Which empire built roads across Europe?", "options": ["Ottoman", "Roman", "Mongol", "Aztec"], "correct": "B", "explanation": "Romans built long straight roads.", "concept": "rome"},
{"q": "A decade is how many years?", "options": ["10", "100", "12", "50"], "correct": "A", "explanation": "A decade is 10 years.", "concept": "history skills"},
{"q": "A century is how many years?", "options": ["10", "50", "100", "1000"], "correct": "C", "explanation": "A century is 100 years.", "concept": "history skills"},
],
"Python": [
{"q": "Which function displays a message in Python?", "options": ["show()", "print()", "display()", "echo()"], "correct": "B", "explanation": "print() displays output, e.g. print('Hello').", "concept": "output"},
{"q": "Which symbol assigns a value to a variable?", "options": ["==", "=", "->", ":="], "correct": "B", "explanation": "Single = assigns, e.g. x = 5. Double == compares.", "concept": "variables"},
{"q": "What does input() do?", "options": ["Prints text", "Reads keyboard text", "Adds numbers", "Stops the program"], "correct": "B", "explanation": "input() reads text typed on the keyboard.", "concept": "input"},
{"q": "What is the result of 7 // 2 in Python?", "options": ["3.5", "3", "4", "2"], "correct": "B", "explanation": "// is floor division: 7 // 2 = 3.", "concept": "operators"},
{"q": "Which keyword starts a loop that repeats while true?", "options": ["for", "if", "while", "repeat"], "correct": "C", "explanation": "while repeats as long as its condition stays True.", "concept": "loops"},
{"q": "How do we check equality in Python?", "options": ["=", "==", "!=", "==="], "correct": "B", "explanation": "== compares two values for equality.", "concept": "conditions"},
{"q": "What type is 'Hello' in Python?", "options": ["int", "float", "str", "bool"], "correct": "C", "explanation": "'Hello' in quotes is a string (str).", "concept": "types"},
{"q": "What type is 13 in Python?", "options": ["str", "int", "float", "list"], "correct": "B", "explanation": "13 without a point is an integer (int).", "concept": "types"},
{"q": "Which line fixes: print('Hi'  ?", "options": ["print('Hi')", "print('Hi'", "Print('Hi')", "print(Hi)"], "correct": "A", "explanation": "Brackets must close: print('Hi').", "concept": "syntax errors"},
{"q": "What does this do? user = 'Claude'", "options": ["Compares user", "Assigns the string Claude to user", "Prints Claude", "Deletes user"], "correct": "B", "explanation": "It assigns (stores) the string in the variable.", "concept": "variables"},
{"q": "Which name is a valid Python variable?", "options": ["2cool", "my-score", "my_score", "my score"], "correct": "C", "explanation": "Variables use letters, digits, underscore and cannot start with a digit or contain spaces/dashes.", "concept": "variables"},
{"q": "What happens after a SyntaxError?", "options": ["Program runs anyway", "Python shows an error and stops that line", "Computer shuts down", "Nothing"], "correct": "B", "explanation": "Python reports the error and does not run the broken line.", "concept": "syntax errors"},
{"q": "Which block runs when if is False and else exists?", "options": ["if block", "else block", "both", "none"], "correct": "B", "explanation": "else runs when the if condition is False.", "concept": "conditions"},
{"q": "How many times does this run? i=0; while i<3: i+=1", "options": ["2", "3", "4", "forever"], "correct": "B", "explanation": "i becomes 1,2,3 then stops: 3 times.", "concept": "loops"},
{"q": "Which function gets the length of a list?", "options": ["size()", "len()", "length()", "count()"], "correct": "B", "explanation": "len() returns the number of items.", "concept": "lists"},
],
}

SUBJECTS = list(QUESTIONS.keys())
SUBJECT_EMOJI = {"Science": "🔬", "Geography": "🌍", "Mathematics": "📐", "History": "🏛️", "Python": "💻"}
